config/web/application.php
config/web/error-handler.php

Waiting: https://github.com/yiisoft/error-handler/pull/25

Fix config due to yiisoft/error-handler changes

---

src/User/UserService.php

See https://github.com/yiisoft/user/pull/24

Adopt to yiisoft/user PR #24

---

.scrutinizer.yml
composer.json
public/index-test.php
public/index.php
src/ApplicationRunner.php

Add ApplicationRunner class

---

config/packages/yiisoft/middleware-dispatcher/config/dist/web.php
config/packages/yiisoft/middleware-dispatcher/config/web.php
yii
yii.bat

| Breaks BC?    | ✔️
| Fixed issues  | https://github.com/yiisoft/yii-demo/issues/112

Move console entry point to app

---

public/index-test.php

Fix #13: Use ApplicationRunnder in index-test.php

---

config/packages/yiisoft/profiler/common.php
config/packages/yiisoft/view/common.php
config/packages/yiisoft/view/web.php
config/params.php
config/web/application.php

Merge after yiisoft/factory#86

Disallow definition objects in configs, except ReferenceInterface

---

config/packages/yiisoft/view/params.php
src/Formatter/ApiResponseFormatter.php

| Fixed issues  | https://github.com/yiisoft/view/issues/156
Waiting: https://github.com/yiisoft/view/pull/157

Update view config params due to yiisoft/view changes

---

src/Auth/AuthRequest.php
src/Blog/EditPostRequest.php

see https://github.com/yiisoft/validator/pull/134

Adopt to new yiisoft/validator

---

composer.json

Add serve command to composer scripts

---

.editorconfig
.github/workflows/build.yml
.github/workflows/static.yml
.scrutinizer.yml
composer.json
docker-compose.yml

Raise minimum PHP requirements to ^8.0

---

composer.json
config/bootstrap.php
config/packages/yiisoft/yii-debug/params.php
config/providers.php
src/ApplicationRunner.php
src/Factory/RestGroupFactory.php

New providers

---

yii.bat

See https://github.com/yiisoft/yii-dev-tool/pull/138

Remove .exe

---

public/index-test.php
public/index.php
src/ApplicationRunner.php
yii

| Fixed issues  | https://github.com/yiisoft/config/pull/73

Adjust config

---

composer.json
config/common/logger.php
config/packages/yiisoft/assets/web.php
config/packages/yiisoft/csrf/web.php
config/packages/yiisoft/user/web.php
config/packages/yiisoft/view/common.php
config/packages/yiisoft/view/params.php
config/packages/yiisoft/view/web.php
config/packages/yiisoft/yii-console/console.php
config/web/application.php

Adopt to `yiisoft/definitions`

---

composer.json
config/delegates-console.php
config/delegates-web.php
config/delegates.php
src/ApplicationRunner.php
yii

| New feature?  | ✔️
| Fixed issues  | https://github.com/yiisoft/di/issues/254

Add delegates config

---

src/Runner/ConfigFactory.php

Fix ConfigFactory

---

config/web/application.php

| Fixed issues  | https://github.com/yiisoft/middleware-dispatcher/issues/43

Adopt to middleware-dispatcher changes

---

.scrutinizer.yml
codeception.yml
public/index.php

Fix scutinizer-ci.

---

composer.json
config/params.php

| Breaks BC?    | ✔️
Waiting: https://github.com/yiisoft/yii-middleware/pull/1

Replace usage of yiisoft/yii-web to yiisoft/yii-http

---

data/nginx/default.conf
tests/acceptance.suite.yml

| New feature?  | ✔️
| Fixed issues  | Fix tests in docker

Fix local tests in docker

---

src/Blog/EditPostRequest.php
src/Blog/ViewPostRequest.php
src/User/UserController.php

:warning: Merge after https://github.com/yiisoft/router/pull/128, https://github.com/yiisoft/request-model/pull/30

Adapt to router changes

---

config/params.php
config/routes.php
src/Blog/EditPostRequest.php

| Fixed issues  | See https://github.com/yiisoft/yii-swagger/pull/48

Adapt to yii-swagger changes

---

composer.json
src/Auth/AuthRequest.php
src/Blog/EditPostRequest.php
tests/acceptance/BlogCest.php

| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

Adapt to request model

---

composer.json
config/web/middleware-dispatcher.php

| Fixed issues  | See https://github.com/yiisoft/request-model/pull/36

Rewrite middleware dispatcher config

---

.github/workflows/build.yml
.github/workflows/static.yml
composer.json

Add PHP 8.1 support to GitHub workflow, update dev-dependencies

---

README.md

Add info to prevent database error to README

---

src/Factory/RestGroupFactory.php

| Fixed issues  | #92 
Adjustment according to #92 to add options

Adjust OPTIONS for RestGroupFactory

---

composer.json
config/params.php
src/Queue/LoggingAuthorizationHandler.php
src/Queue/UserLoggedInMessage.php
src/User/UserService.php

Add queue example usage

---

composer.json

Fixed packages versions and add debugger

---

composer.json
config/common/cycle.php
config/params.php
src/Blog/Post.php
src/User/User.php

| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

Adapt to `yiisoft/yii-cycle`

---

composer.json
config/web/middleware-dispatcher.php

| Fixed issues  | https://github.com/yiisoft/middleware-dispatcher/pull/55

Adapt to `yiisoft/middleware-dispatcher`

---

.github/workflows/build.yml
composer.json

Add intl extension in CI

---

CHANGELOG.md
composer.json
phpunit.xml.dist

Fix tests run
